### ISSUE TITLE
PermissionError: [Errno 13] Permission denied when trying to run a command

### ISSUE THREAD

**Issue by johan-hy** [Textualize/trogon#33]
Somehow I run into "Permission denied" when trying to run any command from tui (running from cli is ok). I get the following trace:

```
$ python3 demo.py tui
Running demo.py add
Traceback (most recent call last):
  File "/home/user/util/demo.py", line 89, in <module>
    cli(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lexxpluss/.local/lib/python3.10/site-packages/trogon/trogon.py", line 292, in wrapped_tui
    Trogon(app, app_name=name, click_context=ctx).run()
  File "/home/lexxpluss/.local/lib/python3.10/site-packages/trogon/trogon.py", line 260, in run
    os.execvp(program_name, arguments)
  File "/usr/lib/python3.10/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.10/os.py", line 615, in _execvpe
    raise saved_exc
  File "/usr/lib/python3.10/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
PermissionError: [Errno 13] Permission denied
```

Any ideas would be helpful?

**Comment by slafs** [comment]
For ad-hoc scripts like this, make sure to check those 3 things:

1. The execute bit is set on the script file (e.g. with `chmod +x demo.py`)
2. The current directory is on your `PATH` env var (e.g. `export PATH=$PATH:.`)
3. The script's first line defines how it should be run (e.g. have `#!/usr/bin/env python` as a first line in the file)

All those allow you to run your script as `demo.py add` (the way Trogon wants to run it). Notice it doesn't run it as `./demo.py ...` (where you don't need #2) nor `python ./demo.py ...` (where all of the above are not needed)

**Comment by johan-hy** [comment]
Thanks! Yes, running it as an executable Python script worked.
