### ISSUE TITLE
Windows Platform - Exec format error [Errno 8]

### ISSUE THREAD

**Issue by 3nthusia5t** [Textualize/trogon#81]
```
(venv) PS F:\machine-learning\testingjupyter> py .\ai.py tui
Running ai.py process
Traceback (most recent call last):
  File "F:\machine-learning\testingjupyter\ai.py", line 68, in <module>
    process()
  File "F:\machine-learning\testingjupyter\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\machine-learning\testingjupyter\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "F:\machine-learning\testingjupyter\venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\machine-learning\testingjupyter\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\machine-learning\testingjupyter\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\machine-learning\testingjupyter\venv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\machine-learning\testingjupyter\venv\Lib\site-packages\trogon\trogon.py", line 296, in wrapped_tui
    Trogon(app, app_name=name, command_name=command, click_context=ctx).run()
  File "F:\machine-learning\testingjupyter\venv\Lib\site-packages\trogon\trogon.py", line 264, in run
    os.execvp(program_name, arguments)
  File "<frozen os>", line 580, in execvp
  File "<frozen os>", line 621, in _execvpe
  File "<frozen os>", line 613, in _execvpe
OSError: [Errno 8] Exec format error
```

![obraz](https://github.com/Textualize/trogon/assets/97202611/681a0649-0bb7-48d7-a200-f7e43fc52987)

I have tried to change the default app for ".py" files as it was set to vs code. It still didn't work. Maybe it is affected by the virtual environment? 

From what i can see on the uploaded picture, the command that is launched is "ai.py <filepath>". Maybe on Windows platform it's more reliable to use "py.exe" launcher?

**Comment by daneah** [comment]
@3nthusia5t thanks for reporting! This appears to be a duplicate of #67. Can you confirm?

**Comment by bigbirdcode** [comment]
Hi, this (and all similar open issues #70 , #67 , ...) are a major problem for me as well. To help the investigation I add my observations:

When I start the script with `python -m my_script tui` then it can run my script well. But when I run with `python my_script.py tui` then the above error happens. Since `click` based scripts are usually not modules, I usually run them with the second way. And so Trogon is failing.
