### ISSUE TITLE
FileNotFoundError when running command via Trogon

### ISSUE THREAD

**Issue by tbham** [Textualize/trogon#9]
When running a command via Trogon, a FileNotFoundError exception is raised. The UI is accessible, arguments and options are configurable, and the CLI application (click) works when running directly. 

My application is running in a venv virtual environment. Trogon and dependencies are installed in the venv. Click was already in use in my project prior to adding Trogon, but it appears all the relevant dependencies meet versioning requirements.

```
Requirement already satisfied: trogon in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (0.2.1)
Requirement already satisfied: click>=8.0.0 in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from trogon) (8.1.2)
Requirement already satisfied: textual>=0.26.0 in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from trogon) (0.26.0)
Requirement already satisfied: colorama in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from click>=8.0.0->trogon) (0.4.4)
Requirement already satisfied: importlib-metadata>=4.11.3 in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from textual>=0.26.0->trogon) (6.6.0)
Requirement already satisfied: markdown-it-py[linkify,plugins]<3.0.0,>=2.1.0 in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from textual>=0.26.0->trogon) (2.2.0)
Requirement already satisfied: rich>=13.3.3 in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from textual>=0.26.0->trogon) (13.3.5)
Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from textual>=0.26.0->trogon) (4.5.0)
Requirement already satisfied: zipp>=0.5 in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from importlib-metadata>=4.11.3->textual>=0.26.0->trogon) (3.15.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from markdown-it-py[linkify,plugins]<3.0.0,>=2.1.0->textual>=0.26.0->trogon) (0.1.2)
Requirement already satisfied: linkify-it-py<3,>=1 in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from markdown-it-py[linkify,plugins]<3.0.0,>=2.1.0->textual>=0.26.0->trogon) (2.0.2)
Requirement already satisfied: mdit-py-plugins in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from markdown-it-py[linkify,plugins]<3.0.0,>=2.1.0->textual>=0.26.0->trogon) (0.3.5)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from rich>=13.3.3->textual>=0.26.0->trogon) (2.15.1)
Requirement already satisfied: uc-micro-py in c:\users\<username>\desktop\vs codium\app\venv\lib\site-packages (from linkify-it-py<3,>=1->markdown-it-py[linkify,plugins]<3.0.0,>=2.1.0->textual>=0.26.0->trogon) (1.0.2)
```

Not certain if this is an issue with my system configuration, or a bug. Installed via pip and imported as shown in the README.

```python
import click
from trogon import tui
from app.cli import run, create_template, version


@tui()
@click.group()
def main() -> None:
    pass


main.add_command(run)
main.add_command(create_template)
main.add_command(version)


if __name__ == "__main__":
    main()
```

```bash
(venv) PS C:\Users\<username>\Desktop\VS Codium\app> python -m app tui
Running python -m app run
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\<username>\Desktop\VS Codium\app\app\__main__.py", line 18, in <module>
    main()
  File "C:\Users\<username>\Desktop\VS Codium\app\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\<username>\Desktop\VS Codium\app\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\<username>\Desktop\VS Codium\app\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\<username>\Desktop\VS Codium\app\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\<username>\Desktop\VS Codium\app\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\<username>\Desktop\VS Codium\app\venv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\<username>\Desktop\VS Codium\app\venv\lib\site-packages\trogon\trogon.py", line 286, in wrapped_tui
    Trogon(app, app_name=name, click_context=ctx).run()
  File "C:\Users\<username>\Desktop\VS Codium\app\venv\lib\site-packages\trogon\trogon.py", line 254, in run
    os.execvp(self.app_name, [self.app_name, *self.post_run_command])
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\os.py", line 574, in execvp
    _execvpe(file, args)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\os.py", line 616, in _execvpe
    raise last_exc
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by tbham** [comment]
Works for me with 0.4.0. Suggest removing trogon and its dependencies and reinstalling. That did it for me.

**Comment by JohLud** [comment]
The issue still exists. Tested on a debian python3.11.0b4 container and trogon 0.4.0.

```
(venv) root@77147b49ef88:/tool# python3 -V
Python 3.11.0b4
(venv) root@77147b49ef88:/tool# python3 tool.py tui
Running tool.py
Traceback (most recent call last):
  File "/tool/tool.py", line 258, in <module>
    cli(obj={})
  File "/tool/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tool/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/tool/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tool/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tool/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tool/venv/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tool/venv/lib/python3.11/site-packages/trogon/trogon.py", line 292, in wrapped_tui
    Trogon(app, app_name=name, click_context=ctx).run()
  File "/tool/venv/lib/python3.11/site-packages/trogon/trogon.py", line 260, in run
    os.execvp(program_name, arguments)
  File "<frozen os>", line 573, in execvp
  File "<frozen os>", line 615, in _execvpe
  File "<frozen os>", line 606, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by darioackermann** [comment]
Workaround for the time being if you don't have any other calls that rely on correct functioning of `os.execvp`:

```python3
from unittest.mock import patch
import os

with patch("os.execvp", side_effect=os.execv):
    app()
```
